---
- name: Add the OS specific variables
  include_vars: '{{ ansible_os_family }}.yml'
  tags: [ 'configuration', 'package', 'service', 'ntp' ]

- name: Install the required packages in Redhat derivatives
  yum: name=ntp state={{ ntp_pkg_state }}
  when: ansible_os_family == 'RedHat'
  tags: [ 'package', 'ntp' ]

- name: Install the required packages in Debian derivatives
  become: yes
  apt: name=ntp state={{ ntp_pkg_state }} update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'
  tags: [ 'package', 'ntp' ]

- name: Install an alternate init script for NTP
  copy: src=etc_init.d_ntp dest=/etc/init.d/ntp mode=0755 owner=root group=root
  when: ansible_os_family == 'Debian'
  tags: [ 'package', 'ntp' ]

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
  - restart ntp
  tags: [ 'configuration', 'package', 'ntp' ]

- name: Start/stop ntp service
  service: name={{ ntp_service_name }} state={{ ntp_service_state }} enabled={{ ntp_service_enabled }} pattern='/ntpd'
  tags: [ 'service', 'ntp' ]
